"use client";

import { useEffect, useState } from "react";
import ProposalCard from "../components/ProposalCard";

type Proposal = {
  id: number;
  title: string;
  action: string;
  confidence: number;
  reasoning: string;
  position_expression: string | null;
  specialists_consulted: string | null;
  proposal_date: string;
  asset_symbol: string | null;
  status: string;
};

const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL ??
  "https://blockrock-backend-production.up.railway.app";

export default function ProposalsPage() {
  const [proposals, setProposals] = useState<Proposal[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchProposals() {
      try {
        const res = await fetch(`${API_BASE_URL}/agents/proposals?limit=50`);
        if (res.ok) {
          setProposals(await res.json());
        }
      } catch (err) {
        console.error("Failed to fetch proposals:", err);
      } finally {
        setLoading(false);
      }
    }
    fetchProposals();
  }, []);

  const sorted = [...proposals].sort(
    (a, b) => new Date(b.proposal_date).getTime() - new Date(a.proposal_date).getTime(),
  );

  return (
    <section className="py-8 sm:py-12">
      <div className="mx-auto max-w-4xl px-4 sm:px-6">
        <div className="mb-8">
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-2">
            Proposals
          </h1>
          <p className="text-text-secondary text-lg">
            Investment theses generated by BlockRock&apos;s team of AI agents to help manage funds.
          </p>
        </div>

        {loading && (
          <div className="text-text-muted text-center py-16 animate-pulse">
            Loading proposals...
          </div>
        )}

        {!loading && proposals.length === 0 && (
          <div className="glass rounded-xl p-8 text-center">
            <p className="text-text-secondary">
              No proposals yet. They&apos;re generated daily after the data pipeline
              refreshes.
            </p>
          </div>
        )}

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {sorted.map((p) => (
            <ProposalCard key={p.id} proposal={p} />
          ))}
        </div>
      </div>
    </section>
  );
}
