"use client";

import { useEffect, useState } from "react";
import ProposalCard from "./ProposalCard";

type Proposal = {
  id: number;
  title: string;
  action: string;
  confidence: number;
  reasoning: string;
  position_expression: string | null;
  specialists_consulted: string | null;
  proposal_date: string;
  asset_symbol: string | null;
  status: string;
};

const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL ??
  "https://blockrock-backend-production.up.railway.app";

export default function ProposalsPanel() {
  const [proposals, setProposals] = useState<Proposal[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchProposals() {
      try {
        const res = await fetch(`${API_BASE_URL}/agents/proposals?limit=10`);
        if (res.ok) {
          setProposals(await res.json());
        }
      } catch (err) {
        console.error("Failed to fetch proposals:", err);
      } finally {
        setLoading(false);
      }
    }
    fetchProposals();
  }, []);

  return (
    <div className="flex flex-col h-full">
      <div className="px-4 py-3 border-b border-glass-border">
        <h3 className="text-sm font-semibold text-text-primary">
          AI Proposals
        </h3>
        <p className="text-xs text-text-muted mt-0.5">
          Daily generated by the agent team
        </p>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-3">
        {loading && (
          <div className="text-xs text-text-muted text-center py-8 animate-pulse">
            Loading proposals...
          </div>
        )}

        {!loading && proposals.length === 0 && (
          <div className="text-xs text-text-muted text-center py-8">
            No proposals yet. They&apos;re generated daily after data refreshes.
          </div>
        )}

        {proposals.map((p) => (
          <ProposalCard key={p.id} proposal={p} />
        ))}
      </div>
    </div>
  );
}
